function top_bt_name_landscape(titl,txtup,txtbot)

% do bottom program name
	h=axes('Units', 'normalized','Position',[.1 .1 .8 .8]);
	axes(h);
	axis off
	h=gca;
 	set(h,'Clipping','off')
	set(h,'FontUnits','points')
	h=text(0., -0.08, [datestr(now,2)],'HorizontalALignment','left',...
        		'FontSize',6,'Units','normalized');

	h=text(0.5,1.08,titl,...
		'HorizontalAlignment','center',...
		'FontSize',10,...
		'Units','normalized'); 

  	h=text(1.1,-0.08,txtbot,...
      		'HorizontalAlignment','right',...
      		'FontSize',6,...
      		'Units','normalized');

 	h=text(1.,1.1,txtup,...
      		'HorizontalAlignment','right',...
      		'FontSize',6,...
      		'Units','normalized');
